site_name: Scoot
theme:
  name: mkdocs
  custom_dir: custom_theme/
  highlightjs: true
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: mkdocs
markdown_extensions:
  - tables
  - markdown_include.include:
      base_path:

    
       .
  - admonition
