site_name: Scoot
theme:
  name: Slate
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - tables
  - markdown_include.include:
      base_path:
    
       .
  - admonition
